### ISSUE TITLE
Working just once

### ISSUE THREAD

**Issue by towerman86** [phpfs/cid_bot#1]
Hi,

I've added the cid_bot to a group and it had worked; now I had to readd it and it doesn't work.
Same thing with a private chat, first time works, other try nothing to do.
Am I wrong? Do I have to wait X hours?
Thanks!

**Comment by phpfs** [comment]
Hi @towerman86 ,

there seems to have been a change in the Telegram API that leads to an empty message payload in some notifications. I've updated the code of cid_bot accordingly and now everything should be back to normal :)
Can you confirm this on your side?

Best, phpfs

**Comment by towerman86** [comment]
> Hi @towerman86 ,
> 
> there seems to have been a change in the Telegram API that leads to an empty message payload in some notifications. I've updated the code of cid_bot accordingly and now everything should be back to normal :)
> Can you confirm this on your side?
> 
> Best, phpfs

Thanks so much, now it works fine :)
